#! /bin/bash

if [ $# -gt 0 ]; then
    if [ -f "$1" ]; then
	file="$1"
    elif [ -d "$1" ]; then
	file="${1}/download.sh"
    else
	echo "dllist: ${1}: No such file or directory"
	exit
    fi
else
    file="download.sh"
fi

cat "$file" | grep axel | grep '"' | cut -d'"' -f2

unset file